use_frameworks!

platform :ios, '8.0'

target 'SDWebImageAVIFCoder_Example' do
  pod 'SDWebImageAVIFCoder', :path => '../'

  target 'SDWebImageAVIFCoder_Tests' do
    inherit! :search_paths

    
  end
end
